### ISSUE TITLE
Suggestion: movie .xml file as text (not binary)

### ISSUE THREAD

**Issue by cdienem** [warpem/warp#11]
Problem: movie xml files are stored in binary format and are complicated to read/modify on unix commandline.

I have come across this already in Warp 1.x. I understand that there are reasons to store things as binary and not plain text. However, it is very hard to access these files on a linux commandline when they are stored as binaries, especially for inexperienced users. So maybe it would be worth switching to plain text if there is no good reason to keep the binary format.

Edit: this also applies to `.settings` files...

**Comment by alisterburt** [comment]
Interesting - I've never had problems but I always interact with these either through VSCode or Python which I guess handle this transparently.

It looks like these files are written from the `SaveMeta` method in unicode with an `XMLTextWriter` class
https://github.com/warpem/warp/blob/30fc4e8b4cbfe5f672cd0df9e65c864ba5a0f14a/WarpLib/Movie.cs#L961-L964

this is provided by `System.Xml`
https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmltextwriter?view=net-8.0

We could change the encoding to Utf-8 easily but I don't have good intuition for how much will break if we do this
https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding?view=net-8.0

I agree that the ability to easily edit these files is important

**Comment by alisterburt** [comment]
@dtegunov any objections to going to UTF if unicode is causing @cdienem issues?

**Comment by cdienem** [comment]
> Interesting - I've never had problems but I always interact with these either through VSCode or Python which I guess handle this transparently.

Most GUI text editors handle these files well, however, `nano`, `more`, `sed` etc. cannot handle them.

When opening them the simplest way in Python, the way I get the contents as a string is

```
f = open("settingsfile.settings", "rb")
data = f.read()
print(data.decode("utf-16")
```

XML parsers of the standard library, however, seem to handle this under the hood (e.g. `xml.etree.ElementTree.parse`).

**Comment by alisterburt** [comment]
makes sense and given that the whole point of WarpTools is to enable users on HPC systems to be effective... we should find a solution

**Comment by alisterburt** [comment]
Just had a chat with @dtegunov - he's going to test changing to UTF-8 and see what it breaks/how hard it would be to move to that. If it's easy, that's what we'll do

**Comment by dtegunov** [comment]
We anticipated this would be a much harder decision when we thought we'd have to drop emoji support due to UTF-8. However, ChatGPT says that all emoji can be represented. With this major obstacle out of the way, here is 773bf9d.

**Comment by cdienem** [comment]
Great, thanks for trying and changing this! I like the suggestion of  `.💩` extensions... :laughing:
