### ISSUE TITLE
Enhancement suggestion: Provide --pretilt option during ts import

### ISSUE THREAD

**Issue by shahpnmlab** [warpem/warp#141]
Currently, Warp tries to determine the 0 tilt automatically, however this can lead to the wrong tilt value to be set as the 0 tilt. Thus it would be useful to provide a flag to override the automatic 0 tilt determination so that the user can exert some control.

**Comment by alisterburt** [comment]
Thanks @shahpnmlab - I agree this would be useful and will add 🙂

**Comment by alisterburt** [comment]
closed by [0dc29a3](https://github.com/warpem/warp/commit/0dc29a3c72897ed994f8140916192557dd17edfa)
