### ISSUE TITLE
issue on large data from julich

### ISSUE THREAD

**Issue by alisterburt** [warpem/warp#142]
David Kartte had some data and was running into issues
He uploaded an image here and I'm going to try to reproduce his issue

https://fz-juelich.sciebo.de/s/ZyCP8eZCD0xVjV4

**Comment by dtegunov** [comment]
They're binning it to 14 A/px, but running CTF estimation up to 7 A. It will fail in this case. We should be more vocal about the mismatch, but still fail rather than silently clip the estimation range.
