### ISSUE TITLE
task: revert Warp to state required for building against PyTorch 1.11

### ISSUE THREAD

**Issue by alisterburt** [warpem/warp#15]
With @dtegunov we have decided that we will revert to building against `PyTorch=1.13` as getting a conda environment going with a CUDA build of `PyTorch>2` seems difficult from computers without nvidia drivers installed/activated. c.f. #3 

We are aware that this may complicate our lives later when we want to develop using `PyTorch>2` and are knowingly taking on this technical debt to enable users to get up and running now.

**Comment by dtegunov** [comment]
Probably 1.11, since 1.13 had conflicts with other packages in the environment suggested in https://github.com/warpem/warp/issues/3#issuecomment-2067907834
