### ISSUE TITLE
template matching peak positions question

### ISSUE THREAD

**Issue by shahpnmlab** [warpem/warp#182]
Working with the test apoF dataset and I am observing that although the peaks following template matching are well centered in the molecule the exported coordinates have a consistent shift. I am reporting this from within WarpTools commit -afe0bdce289eebe2c67339a180bae18e9895a628

The data were processed using the supplied e2e.sh script, with a slight modification in the particle extraction step. The command is as follows -
```
# Write out 2D 'particle series' images for 3D refinement
WarpTools ts_export_particles \
--settings warp_tiltseries.settings \
--input_directory warp_tiltseries/matching \
--input_pattern "*15854_clean.star" \
--normalized_coords \
--output_star relion/matching.star \
--output_angpix 10 \
--box 32 \
--diameter 130 \
--relative_output_paths \
--3d
```

There is a consistent offset in where the coordinates for the peak are and where the reported coords are in the star file.
In attached image, the top row is me eye-balling the peak intensity and the bottom row are the coordinates reported in the star file rounded to the nearest integer. The coords specifically highlighted in the image is -
 `64.861  415.615  18.199          45   5.850267   74.99999   TS_1.tomostar  10000.0  10.00000  4.5    ../warp_tiltseries/subtomo/TS_1/TS_1_0000005_10.00A.mrc    ../warp_tiltseries/subtomo/TS_1/TS_1_0000005_ctf_10.00A.mrc  10.00000  300.000  2.700`.
<img width="1382" alt="image" src="https://github.com/warpem/warp/assets/34034134/4a27a665-51fb-4348-a36d-0de3ce1792a1">

The off-centered-ness manifests in the extracted subtomo as well 
<img width="196" alt="image" src="https://github.com/warpem/warp/assets/34034134/644dc0b7-4f34-4502-82ca-248baa4e26c2">

Let me know if you need the full star file happy to send that over as well.

**Comment by alisterburt** [comment]
interesting - is the reference correctly centered?

**Comment by shahpnmlab** [comment]
Presumably? I am simply downloading emd_15854...

**Comment by alisterburt** [comment]
what's the magnitude of the shift between your eyeballed maximum and the offset?

IMOD 1 indexes coordinates, RELION coordinates are zero indexed, that gives a difference of ~1.7px already in 3d

I agree something seems a little off, maybe the way the template is rescaled doesn't keep it centered?

**Comment by shahpnmlab** [comment]
Ah good to know that RELION 0-indexes. Let me measure and get back to you...

**Comment by shahpnmlab** [comment]
OK yeah the measured the distance and the  diff is ~1.7px
<img width="1005" alt="image" src="https://github.com/warpem/warp/assets/34034134/7194cf8b-0902-47a7-9cdc-15aeb224066f">

The position looked worse in IMOD ebcause I was not aware of the indexing characteristics of relion.

**Comment by alisterburt** [comment]
no worries, thanks for reporting back! 1.7px is big when pixels are 1nm 😂

**Comment by alisterburt** [comment]
to summarise, the probem was with the way pranav was visualising RELION metadata in IMOD
