### ISSUE TITLE
Template matching fully covered voxels is too strict

### ISSUE THREAD

**Issue by alisterburt** [warpem/warp#193]
Current criteria are that voxels must be in all tilts to be included - this seems too strict, maybe 80% is better

**Comment by shahpnmlab** [comment]
In addition to default thresholds, the option to turn it off would also be good to have (like in the GUI versions)

**Comment by asarnow** [comment]
Agree with @shahpnmlab, if we use the tomograms for traditional STA or other 3D analysis there is no need to restrict the matching volume.

**Comment by shahpnmlab** [comment]
> Agree with @shahpnmlab, if we use the tomograms for traditional STA or other 3D analysis there is no need to restrict the matching volume.

@asarnow 
My fork for TS matching has this option 
`https://github.com/shahpnmlab/warp/blob/b98b31ef0823c569fa7dd85cdb45136c4dc15bd5/WarpTools/Commands/Tiltseries/TemplateMatchTiltseries.cs#L67`
However, it probably is a good idea to wait until @alisterburt or @dtegunov integrate it into the main branch.

**Comment by dtegunov** [comment]
--max_missing_tilts in ts_template_match defaults to 2 now.
