### ISSUE TITLE
WarpTools ts_import_alignments: Minor bug when importing tilt alignments without the right .tlt present

### ISSUE THREAD

**Issue by rkjensen** [warpem/warp#225]
When using WarpTools ts_import_alignments, and the .tlt file is not present in the correct folder you get the error:

"Failed to import alignments for 00036.tomostar: Could not find 00036.xf"

Instead of the real error which is that it could not find 00036.tlt

**Comment by alisterburt** [comment]
Good point, thanks @rkjensen !
