### ISSUE TITLE
wrpDose values in .tomostar not consistent with warp1.0

### ISSUE THREAD

**Issue by nkjaerjensen** [warpem/warp#274]
Hi Alister/Dimitry,

Awesome to see you are working on warp2.0, really excited to follow the development!

I have noticed that .tomostar files produced by warp1.0 (windows) use half the dose per tilt (i.e. a kind of median dose experienced by the movie) as the initial wrpDose value when a default dose per tilt is specified in the GUI. I.e., if a default dose per tilt value of fx 4 e/A^2 is specified, then the first, untilted movie has a wrpDose value of 2, and the next movie has a value of 6. However, in warp2.0 (WarpTools, linux), the .tomostar files produced by the same dose per tilt value (using ts_import) use the dose experienced by the sample at the start of the movie as the initial wrpDose value. I.e. if a dose per tilt value of fx 4 e/A^2 is used, then the first, untilted movie has a wrpDose value of 0, and the next movie has a value of 4.

Is this intentional? Is the dose weighting treated differently?

PS: for your convenience, I believe the relevant code snippets are: lines 233-239 in DialogTomoImportImod.xaml.cs, warp 1.0:
`
                            // In case mdoc doesn't tell anything about the dose, use default value
                            if (_Dose > 0)
                                for (int i = 0; i < SortedTime.Count; i++)
                                {
                                    SortedTime[i].Dose = (i + 0.5f) * (float)_Dose;
                                    Accumulated += (float)_Dose;
                                }`

And lines 262-264 in ImportTiltseries.cs, warp2.0:
`                        // Replace exposure value with accumulated per-tilt exposure based on --tilt_exposure
                        for (int i = 0; i < SortedTime.Count; i++)
                            SortedTime[i].Dose = i * (float)CLI.TiltExposure;`

All the best,
// Nicolas

**Comment by alisterburt** [comment]
Hey @nkjaerjensen ! Good spot - I'm not sure if it was intentional or not. It's a tough call which is the better choice overall: the old implementation has a smaller error per frame but downweights potentially useful information in earlier frames more...

In any case, the differences are relatively small and the b-factor/dose relationship is based on a simple heuristic and is likely not too accurate in the first place 😆
