### ISSUE TITLE
import tilt series not working

### ISSUE THREAD

**Issue by hmalvezzi** [warpem/warp#307]
Hi!
I have the windows version of warp 1.0.9
I'm trying to create stacks for imod, but no .mrc files was created. Once the stacks are being created the .mrc.rawltl and .mrc.st files appear in the new imod folder, but only that. Any suggestions?
Thanks, 
H

**Comment by alisterburt** [comment]
Hi @hmalvezzi - that is the expected outcome, I'm not sure what you were expecting that is different...
