### ISSUE TITLE
Individually deselecting tilts without an existing list?

### ISSUE THREAD

**Issue by jmdobbs** [warpem/warp#31]
Hi,

Doing some testing, it seems like there is no way to individually select or deselect tilts (or tomostars) in the CLI version, unless you already know exactly which of those to exclude via the input_data additional option. Is this correct?

Thanks for the great work!!
Joe.

**Comment by alisterburt** [comment]
Hey @jmdobbs - thanks for opening this issue!

I'm glad you found the automated routines in `ts_import` and `ts_aretomo`

One route to excluding tilts that are bad in the way you describe is to run BoxNet and use `filter_quality` WarpTool to remove frame series based on the percentage of rubbish in the generated masks 

https://github.com/warpem/warp/blob/090a5a28c017a08eb2292e29219d36d5b98dbfed/WarpTools/Commands/General/FilterQuality.cs#L43-L45

This obviously relies on having a BoxNet model which works well for masking high contrast rubbish.

@dtegunov I had a quick poke around the internet and realised we don't provide a pre-trained model - do we have one somewhere? Should we retrain one?

**Comment by jmdobbs** [comment]
Hi @alisterburt. I'd considered this possibility, but found that our usual boxnet was not working so well. Are there meant to be any issues with performance for boxnet models trained on windows but applied in linux? See attached for comparison of the same boxnet model on the same tilt.
![Picture2](https://github.com/warpem/warp/assets/87859107/8eee7423-f667-47d5-8eaa-7c6a7394812f)
