### ISSUE TITLE
Aretomo/warp compatibility flags possibly wrong in job submission

### ISSUE THREAD

**Issue by jmdobbs** [warpem/warp#41]
Hi,
With the update from yesterday, aretomo is now running fine. However, warp is unable to find the .xf file. I think this may because the wrong --outimod flag is passed during the job submission. The job passes outimod 1, whereas the usual flag for compatibility with warp is --outimod 2
 --outxf is also set to 0 by default (should possibly be 1?)

024-05-01 07:28:48.217 Executing AreTomo2 in /struct/mahamid/jdobbs/warp2_testing/data_gseries/processing/tiltstack/gTS_003 with arguments: -InMrc gTS_003.st -AngFile gTS_003.rawtlt -VolZ 0 -OutBin 0 -TiltAxis 85.2 -1 -AlignZ 100 -TiltCor 1 **-OutImod 1** -DarkTol 0 -OutMrc gTS_003_aligned.mrc -Gpu 0

**Comment by jmdobbs** [comment]
Odd, it's AreTomo2 here but the flags should be the same. The AreTomo --help for 1.3, like for 2.0, says that --outImod 1 should only generate imod files for relion4, not warp

**Comment by alisterburt** [comment]
Could you attempt with 1.3.4 and report back? If I don't hear back I'll close this in a few days as it appears Warp is working as expected here

**Comment by dtegunov** [comment]
The flags were working as described in the docs until some version, then I updated to 1.3.4 and had to change them to get anything useful. It's makes sense that they fixed this bug in a later version. That's what we get by relying on buggy behavior.

However, I also saw another WarpTools bug when testing this yesterday where it complained about not finding the .xf when I specified --output_processing. Are you possibly running into this one? I'll look into it today.

**Comment by jmdobbs** [comment]
That makes sense, I used 1.3.0 and 2.0 and got the same results. We don't have 1.3.4 installed.

The exact command I ran was 
WarpTools ts_aretomo --settings TS_settings.settings --angpix 20 --alignz 2000 --min_fov 0.5

**Comment by jmdobbs** [comment]
from the testing @ThomasHoffmann77 and I have done: even with aretomo1.3.4 the warp flags produce the incorrect result, our aretomo installation (with suffix Cuda118) appears to behave according to the docs

**Comment by jmdobbs** [comment]
Thomas was able to patch our module to use --outimod 2, and this did not change the behavior (or created files at all). However, this allowed us to recognize that it was the formatting of the generated files that was wrong. Running aretomo with these parameters (above) generated gTS_003_st.xf, where warp needs gTS_003.xf

**Comment by alisterburt** [comment]
@jmdobbs I'm going to update our wrapper to work with AreTomo2 which should fix this - please hold 🙂

**Comment by alisterburt** [comment]
closed by #57
