### ISSUE TITLE
Running MCore from subdirectory hangs infinitely on "Loading population..."

### ISSUE THREAD

**Issue by rbs-sci** [warpem/warp#49]
Minor quality of life request/pseudo-bug.

Certainly non-critical.

I `cd`'d into the`m` directory then accidentally ran `MCore` (for a refinement) from there rather than the project directory; rather than crash or complain it couldn't find what I'd asked it to work on, it just sat on "Loading population..." until I killed it (five or six minutes, my eyes needed a break) - it would be nice for it to throw a message up suggesting the data couldn't be found, as until I checked `top` I thought it was actually doing something.

**Comment by alisterburt** [comment]
thanks for the report @rbs-sci ! Agree this would be nice 🙂

**Comment by dtegunov** [comment]
Check added. 

(It was a larger bug where any exceptions thrown in DoProcessing were swallowed silently.)
