### ISSUE TITLE
Deconvolved tomograms all slices identical

### ISSUE THREAD

**Issue by asarnow** [warpem/warp#59]
The raw tomograms look normal, but the ones in `warp_tiltseries/reconstruction/deconv` appear to be composed entirely of one (central?) slice. They have the expected dimension, but all the slices look the same.

**Comment by alisterburt** [comment]
Thanks for the report @asarnow - I'm unable to reproduce right now but this is because of problems in my own dev environment, will have to fix and retry later

**Comment by asarnow** [comment]
I think there were some issues in my project, AreTomo2 was used without the compatibility patches before. I'm repeating ts_aretomo through ts_reconstruct now.

**Comment by dtegunov** [comment]
Did it end up keeping only the 0 tilt?

**Comment by asarnow** [comment]
I've re-run with the AreTomo2 patches and my regular tomograms look good, but the deconvolved ones are still just a single image repeated across all slices.

**Comment by dtegunov** [comment]
Fixed in 08510e6
