### ISSUE TITLE
task: update e2e script/docs to not flip tilt angles during import

### ISSUE THREAD

**Issue by dmichalak** [warpem/warp#74]
I'm running through the provided script and currently at the steps involving refinement in M. Comparing the map to EMD-11603 and PDB: 5N27, it looks like my map has opposite handedness. This is also the case for the initial refined map output from RELION5.

Does a convention change between RELION versions?

**Comment by alisterburt** [comment]
Hey @dmichalak - I just checked and I also got inverted handedness, thanks for flagging this

I don't think this is to do with RELION conventions, it's an error in either
- tilt axis angle (off by 180)
- some 2D image flip somewhere

**Comment by dtegunov** [comment]
We should update the script not to flip the tilt angles during import.
